version: "3"

services:
  dns:
    image: ragibkl/adblock_dns
    restart: always
    ports:
      - 1153:53/tcp
      - 1153:53/udp
    environment:
      CONFIG_URL: /local-data/configuration.yaml
      FQDN: dns.localhost.localdomain
      IPV4: 0.0.0.0
      IPv6: "::"
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "20"
    volumes:
      - ./data:/local-data
      - logs:/logs

  dnsdist:
    image: ragibkl/adblock_dnsdist
    restart: always
    network_mode: host
    environment:
      TLS_ENABLED: "false"
      BACKEND_PORT: "1153"
      PORT: "1154"
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "20"
    volumes:
      - logs:/logs

  dnsdist_logs:
    image: ragibkl/adblock_dnsdist_logs
    restart: always
    network_mode: host
    environment:
      LOG_FILE: /logs/logs.yaml
      PORT: "8080"
    volumes:
      - logs:/logs

volumes:
  logs:
